# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89f3ce64f63aeab952c21901efb1eb94ff6df66b5a0580d2f71925afb23812a695767e920e95e29c790639911d1a180d828e5135db508629d6ff33e051672073

test:
  secret_key_base: 41566c9f8a12d26732bdb0e2f11b1ced8a0ff58d5f748f099894d7db0190d48d02cf26e98db1773788f17d216cc706d1b61262aa8eadfaa49629e5e282425062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
